### ISSUE TITLE
Site is not responsive for mobile and various monitor sizes

### ISSUE THREAD

**Issue by gregoriB** [harrylincoln/notate#10]
Responsive styling is needed.  Tab lines(strings) wrapping makes the tab unusable.

**Comment by harrylincoln** [comment]
Site was never made to be responsive - using the mouse/trackpad is mandatory to plot the notes.

**Comment by gregoriB** [comment]
Fair point, but when I use the display emulator in the chrome dev tools for 4k and UW displays resolutions, the lines are wrapping for some reason.  Not sure if that happens on those actual displays.

**Comment by harrylincoln** [comment]
@gregoriB have updated it to be at least readable on larger screen sizes! Many thanks for your issue submit!
