### ISSUE TITLE
Quarter note dyad bug🕷 

### ISSUE THREAD

**Issue by spyderspyders** [harrylincoln/notate#19]
Thanks for your time and hard work. 

I think I found a bug. 🐜 

I made two quarter note dyads 

A          E

C          A 

And ended up with 12 string tab.

**Comment by harrylincoln** [comment]
HI there! Sounds like you could be using it on screenwidth that makes a bar stack?

**Comment by spyderspyders** [comment]
iPhone safari iOS 12.4.3

**Comment by harrylincolnPE** [comment]
Ah I see - this app isn't mobile friendly so that's probably why 👍 See common gotchas section on the startup screen.

**Comment by harrylincoln** [comment]
Ah I see - this app isn't mobile friendly so that's probably why 👍 See common gotchas section on the startup screen.
